# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_device_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDeviceDialog(object):
    def setupUi(self, AddDeviceDialog):
        AddDeviceDialog.setObjectName("AddDeviceDialog")
        AddDeviceDialog.resize(524, 352)
        AddDeviceDialog.setMinimumSize(QtCore.QSize(524, 352))
        AddDeviceDialog.setMaximumSize(QtCore.QSize(524, 352))
        self.label = QtWidgets.QLabel(AddDeviceDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddDeviceDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label_2.setObjectName("label_2")
        self.line_edit_device_id = QtWidgets.QLineEdit(AddDeviceDialog)
        self.line_edit_device_id.setGeometry(QtCore.QRect(130, 10, 381, 21))
        self.line_edit_device_id.setObjectName("line_edit_device_id")
        self.line_edit_entity_name = QtWidgets.QLineEdit(AddDeviceDialog)
        self.line_edit_entity_name.setGeometry(QtCore.QRect(130, 40, 381, 21))
        self.line_edit_entity_name.setObjectName("line_edit_entity_name")
        self.label_3 = QtWidgets.QLabel(AddDeviceDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.label_3.setObjectName("label_3")
        self.combo_box_entity_type = QtWidgets.QComboBox(AddDeviceDialog)
        self.combo_box_entity_type.setGeometry(QtCore.QRect(130, 70, 381, 22))
        self.combo_box_entity_type.setObjectName("combo_box_entity_type")
        self.label_4 = QtWidgets.QLabel(AddDeviceDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_4.setObjectName("label_4")
        self.scroll_area_dynamic_device_attrs = QtWidgets.QScrollArea(AddDeviceDialog)
        self.scroll_area_dynamic_device_attrs.setEnabled(True)
        self.scroll_area_dynamic_device_attrs.setGeometry(QtCore.QRect(130, 100, 381, 201))
        self.scroll_area_dynamic_device_attrs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area_dynamic_device_attrs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area_dynamic_device_attrs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scroll_area_dynamic_device_attrs.setWidgetResizable(True)
        self.scroll_area_dynamic_device_attrs.setObjectName("scroll_area_dynamic_device_attrs")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 362, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area_dynamic_device_attrs.setWidget(self.scrollAreaWidgetContents)
        self.button_ok = QtWidgets.QPushButton(AddDeviceDialog)
        self.button_ok.setGeometry(QtCore.QRect(355, 310, 75, 23))
        self.button_ok.setObjectName("button_ok")
        self.button_cancel = QtWidgets.QPushButton(AddDeviceDialog)
        self.button_cancel.setGeometry(QtCore.QRect(435, 310, 75, 23))
        self.button_cancel.setObjectName("button_cancel")

        self.retranslateUi(AddDeviceDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDeviceDialog)

    def retranslateUi(self, AddDeviceDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDeviceDialog.setWindowTitle(_translate("AddDeviceDialog", "Dialog"))
        self.label.setText(_translate("AddDeviceDialog", "Device id"))
        self.label_2.setText(_translate("AddDeviceDialog", "Entity name"))
        self.label_3.setText(_translate("AddDeviceDialog", "Entity type"))
        self.label_4.setText(_translate("AddDeviceDialog", "Dynamic attributes"))
        self.button_ok.setText(_translate("AddDeviceDialog", "Ok"))
        self.button_cancel.setText(_translate("AddDeviceDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDeviceDialog = QtWidgets.QDialog()
    ui = Ui_AddDeviceDialog()
    ui.setupUi(AddDeviceDialog)
    AddDeviceDialog.show()
    sys.exit(app.exec_())
