# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_relationship_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRelationshipDialog(object):
    def setupUi(self, AddRelationshipDialog):
        AddRelationshipDialog.setObjectName("AddRelationshipDialog")
        AddRelationshipDialog.resize(505, 230)
        AddRelationshipDialog.setMinimumSize(QtCore.QSize(505, 230))
        AddRelationshipDialog.setMaximumSize(QtCore.QSize(505, 230))
        self.label = QtWidgets.QLabel(AddRelationshipDialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddRelationshipDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddRelationshipDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_3.setObjectName("label_3")
        self.combo_box_first_entity = QtWidgets.QComboBox(AddRelationshipDialog)
        self.combo_box_first_entity.setGeometry(QtCore.QRect(130, 20, 361, 22))
        self.combo_box_first_entity.setObjectName("combo_box_first_entity")
        self.combo_box_relationship_type = QtWidgets.QComboBox(AddRelationshipDialog)
        self.combo_box_relationship_type.setGeometry(QtCore.QRect(130, 80, 361, 21))
        self.combo_box_relationship_type.setObjectName("combo_box_relationship_type")
        self.combo_box_ref_entity = QtWidgets.QComboBox(AddRelationshipDialog)
        self.combo_box_ref_entity.setGeometry(QtCore.QRect(130, 50, 361, 21))
        self.combo_box_ref_entity.setObjectName("combo_box_ref_entity")
        self.button_cancel = QtWidgets.QPushButton(AddRelationshipDialog)
        self.button_cancel.setGeometry(QtCore.QRect(415, 190, 75, 23))
        self.button_cancel.setObjectName("button_cancel")
        self.button_add_relationship = QtWidgets.QPushButton(AddRelationshipDialog)
        self.button_add_relationship.setGeometry(QtCore.QRect(335, 190, 75, 23))
        self.button_add_relationship.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_add_relationship.setObjectName("button_add_relationship")
        self.label_4 = QtWidgets.QLabel(AddRelationshipDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_4.setObjectName("label_4")
        self.text_edit_definition = QtWidgets.QTextEdit(AddRelationshipDialog)
        self.text_edit_definition.setGeometry(QtCore.QRect(130, 110, 361, 71))
        self.text_edit_definition.setObjectName("text_edit_definition")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.combo_box_first_entity.raise_()
        self.combo_box_relationship_type.raise_()
        self.combo_box_ref_entity.raise_()
        self.label_4.raise_()
        self.text_edit_definition.raise_()
        self.button_cancel.raise_()
        self.button_add_relationship.raise_()

        self.retranslateUi(AddRelationshipDialog)
        QtCore.QMetaObject.connectSlotsByName(AddRelationshipDialog)

    def retranslateUi(self, AddRelationshipDialog):
        _translate = QtCore.QCoreApplication.translate
        AddRelationshipDialog.setWindowTitle(_translate("AddRelationshipDialog", "Dialog"))
        self.label.setText(_translate("AddRelationshipDialog", "Entity 1"))
        self.label_2.setText(_translate("AddRelationshipDialog", "Relationship type"))
        self.label_3.setText(_translate("AddRelationshipDialog", "Entity 2"))
        self.button_cancel.setText(_translate("AddRelationshipDialog", "Cancel"))
        self.button_add_relationship.setText(_translate("AddRelationshipDialog", "Add"))
        self.label_4.setText(_translate("AddRelationshipDialog", "Definition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddRelationshipDialog = QtWidgets.QDialog()
    ui = Ui_AddRelationshipDialog()
    ui.setupUi(AddRelationshipDialog)
    AddRelationshipDialog.show()
    sys.exit(app.exec_())
