# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dynamic_device_attrs_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DynamicDeviceAttrsWidget(object):
    def setupUi(self, DynamicDeviceAttrsWidget):
        DynamicDeviceAttrsWidget.setObjectName("DynamicDeviceAttrsWidget")
        DynamicDeviceAttrsWidget.resize(243, 231)
        DynamicDeviceAttrsWidget.setMinimumSize(QtCore.QSize(243, 0))
        self.check_box_temperature = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_temperature.setGeometry(QtCore.QRect(10, 10, 221, 21))
        self.check_box_temperature.setObjectName("check_box_temperature")
        self.check_box_pressure = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_pressure.setGeometry(QtCore.QRect(10, 100, 221, 21))
        self.check_box_pressure.setMinimumSize(QtCore.QSize(221, 21))
        self.check_box_pressure.setObjectName("check_box_pressure")
        self.check_box_power = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_power.setGeometry(QtCore.QRect(10, 130, 221, 21))
        self.check_box_power.setObjectName("check_box_power")
        self.check_box_volume_flow = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_volume_flow.setGeometry(QtCore.QRect(10, 160, 221, 21))
        self.check_box_volume_flow.setObjectName("check_box_volume_flow")
        self.check_box_temperature_in = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_temperature_in.setGeometry(QtCore.QRect(10, 40, 221, 21))
        self.check_box_temperature_in.setObjectName("check_box_temperature_in")
        self.check_box_temperature_out = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_temperature_out.setGeometry(QtCore.QRect(10, 70, 221, 21))
        self.check_box_temperature_out.setObjectName("check_box_temperature_out")
        self.check_box_conversion_efficiency = QtWidgets.QCheckBox(DynamicDeviceAttrsWidget)
        self.check_box_conversion_efficiency.setGeometry(QtCore.QRect(10, 190, 221, 21))
        self.check_box_conversion_efficiency.setObjectName("check_box_conversion_efficiency")

        self.retranslateUi(DynamicDeviceAttrsWidget)
        QtCore.QMetaObject.connectSlotsByName(DynamicDeviceAttrsWidget)

    def retranslateUi(self, DynamicDeviceAttrsWidget):
        _translate = QtCore.QCoreApplication.translate
        DynamicDeviceAttrsWidget.setWindowTitle(_translate("DynamicDeviceAttrsWidget", "Form"))
        self.check_box_temperature.setText(_translate("DynamicDeviceAttrsWidget", "temperature"))
        self.check_box_pressure.setText(_translate("DynamicDeviceAttrsWidget", "pressure"))
        self.check_box_power.setText(_translate("DynamicDeviceAttrsWidget", "power"))
        self.check_box_volume_flow.setText(_translate("DynamicDeviceAttrsWidget", "volume flow"))
        self.check_box_temperature_in.setText(_translate("DynamicDeviceAttrsWidget", "temperature in"))
        self.check_box_temperature_out.setText(_translate("DynamicDeviceAttrsWidget", "temperature_out"))
        self.check_box_conversion_efficiency.setText(_translate("DynamicDeviceAttrsWidget", "conversion efficiency"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DynamicDeviceAttrsWidget = QtWidgets.QWidget()
    ui = Ui_DynamicDeviceAttrsWidget()
    ui.setupUi(DynamicDeviceAttrsWidget)
    DynamicDeviceAttrsWidget.show()
    sys.exit(app.exec_())
