# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parse_fmu_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParseFmuDialog(object):
    def setupUi(self, ParseFmuDialog):
        ParseFmuDialog.setObjectName("ParseFmuDialog")
        ParseFmuDialog.resize(601, 720)
        ParseFmuDialog.setMinimumSize(QtCore.QSize(500, 600))
        self.gridLayout = QtWidgets.QGridLayout(ParseFmuDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ParseFmuDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.text_edit_entities_and_relationships = QtWidgets.QTextEdit(ParseFmuDialog)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.text_edit_entities_and_relationships.setFont(font)
        self.text_edit_entities_and_relationships.setReadOnly(True)
        self.text_edit_entities_and_relationships.setObjectName("text_edit_entities_and_relationships")
        self.gridLayout.addWidget(self.text_edit_entities_and_relationships, 3, 0, 1, 3)
        self.button_cancel = QtWidgets.QPushButton(ParseFmuDialog)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.button_ok = QtWidgets.QPushButton(ParseFmuDialog)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 4, 1, 1, 1)
        self.text_edit_fmu_info = QtWidgets.QTextEdit(ParseFmuDialog)
        self.text_edit_fmu_info.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.text_edit_fmu_info.setFont(font)
        self.text_edit_fmu_info.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.text_edit_fmu_info.setReadOnly(True)
        self.text_edit_fmu_info.setObjectName("text_edit_fmu_info")
        self.gridLayout.addWidget(self.text_edit_fmu_info, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(ParseFmuDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        self.retranslateUi(ParseFmuDialog)
        QtCore.QMetaObject.connectSlotsByName(ParseFmuDialog)

    def retranslateUi(self, ParseFmuDialog):
        _translate = QtCore.QCoreApplication.translate
        ParseFmuDialog.setWindowTitle(_translate("ParseFmuDialog", "Dialog"))
        self.label_2.setText(_translate("ParseFmuDialog", "Identified entities and relationships:"))
        self.button_cancel.setText(_translate("ParseFmuDialog", "Cancel"))
        self.button_ok.setText(_translate("ParseFmuDialog", "Ok"))
        self.label.setText(_translate("ParseFmuDialog", "Model Information:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ParseFmuDialog = QtWidgets.QDialog()
    ui = Ui_ParseFmuDialog()
    ui.setupUi(ParseFmuDialog)
    ParseFmuDialog.show()
    sys.exit(app.exec_())
