# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startup_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartupDialog(object):
    def setupUi(self, StartupDialog):
        StartupDialog.setObjectName("StartupDialog")
        StartupDialog.resize(373, 175)
        self.label = QtWidgets.QLabel(StartupDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 41))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(StartupDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 351, 21))
        self.label_2.setObjectName("label_2")
        self.line_edit_bes_id = QtWidgets.QLineEdit(StartupDialog)
        self.line_edit_bes_id.setGeometry(QtCore.QRect(10, 80, 351, 21))
        self.line_edit_bes_id.setObjectName("line_edit_bes_id")
        self.button_ok = QtWidgets.QPushButton(StartupDialog)
        self.button_ok.setGeometry(QtCore.QRect(285, 130, 75, 23))
        self.button_ok.setObjectName("button_ok")

        self.retranslateUi(StartupDialog)
        QtCore.QMetaObject.connectSlotsByName(StartupDialog)

    def retranslateUi(self, StartupDialog):
        _translate = QtCore.QCoreApplication.translate
        StartupDialog.setWindowTitle(_translate("StartupDialog", "Dialog"))
        self.label.setText(_translate("StartupDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Welcome to FiBEM</span></p></body></html>"))
        self.label_2.setText(_translate("StartupDialog", "Enter an id for your building energy system:"))
        self.button_ok.setText(_translate("StartupDialog", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartupDialog = QtWidgets.QDialog()
    ui = Ui_StartupDialog()
    ui.setupUi(StartupDialog)
    StartupDialog.show()
    sys.exit(app.exec_())
